import { Profile, Idea, Project, Hackathon, Company, Connection, Message, Notification, Conversation } from "@/types";

export const MOCK_CURRENT_USER: Profile = {
  id: "usr_curr_1",
  username: "alexchen",
  full_name: "Alex Chen",
  avatar_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
  headline: "Full-Stack Engineer & AI Systems Architect | Building IdeaEra",
  bio: "Passionate about autonomous agent ecosystems, collaborative web interfaces, and distributed systems. Always exploring the intersection of creative tooling and human-machine synergy.",
  location: "San Francisco, CA",
  website: "https://alexchen.dev",
  github_url: "https://github.com/alexchen-dev",
  linkedin_url: "https://linkedin.com/in/alexchen-dev",
  skills: ["Next.js", "TypeScript", "Python", "AI / LLMs", "PostgreSQL", "Tailwind CSS", "Docker", "PyTorch"],
  interests: ["Generative AI", "Developer Tooling", "Spatial Computing", "Open Source", "Autonomous Robotics"],
  created_at: "2025-01-15T10:00:00Z",
  updated_at: "2026-03-01T12:00:00Z",
};

export const MOCK_PEOPLE: Profile[] = [
  MOCK_CURRENT_USER,
  {
    id: "usr_2",
    username: "sarah_kim",
    full_name: "Sarah Kim",
    avatar_url: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80",
    headline: "Product Designer & Design Systems Lead @ VoxelForge",
    bio: "Obsessed with micro-interactions, spatial design paradigms, and high-fidelity typography. Mentoring aspiring designers and founders.",
    location: "New York, NY",
    website: "https://sarahkim.design",
    github_url: "https://github.com/sarahkim",
    linkedin_url: "https://linkedin.com/in/sarahkimdesign",
    skills: ["UI/UX Design", "Figma", "Design Systems", "Tailwind CSS", "React", "User Research"],
    interests: ["Design Tools", "Spatial UI", "Accessibility", "Creative Coding"],
    created_at: "2025-02-10T14:30:00Z",
    updated_at: "2026-02-28T09:15:00Z",
    connection_status: "connected",
    mutual_connections_count: 8,
  },
  {
    id: "usr_3",
    username: "marcus_vance",
    full_name: "Marcus Vance",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    headline: "Distributed Systems & Rust Core Engineer | Ex-Stripe",
    bio: "Building low-latency database engines and verifiable computing primitives. Interested in high-throughput data streaming and Raft consensus.",
    location: "Seattle, WA",
    website: "https://marcusvance.io",
    github_url: "https://github.com/marcusvance",
    linkedin_url: "https://linkedin.com/in/marcusvance",
    skills: ["Rust", "Go", "Distributed Systems", "Kubernetes", "PostgreSQL", "Web3 / Solidity"],
    interests: ["Consensus Protocols", "Database Internals", "Zero-Knowledge Proofs", "Open Infrastructure"],
    created_at: "2025-01-20T18:00:00Z",
    updated_at: "2026-03-02T16:45:00Z",
    connection_status: "pending_received",
    mutual_connections_count: 5,
  },
  {
    id: "usr_4",
    username: "elena_rostova",
    full_name: "Elena Rostova",
    avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80",
    headline: "AI Research Scientist | Multimodal LLMs & Autonomous Agents",
    bio: "PhD in Machine Learning from Stanford. Exploring test-time reasoning compute, synthetic dataset synthesis, and robotic perception.",
    location: "Palo Alto, CA",
    website: "https://elenarostova.ai",
    github_url: "https://github.com/elenarostova",
    linkedin_url: "https://linkedin.com/in/elenarostova",
    skills: ["Python", "PyTorch", "AI / LLMs", "Machine Learning", "Computer Vision", "Data Engineering"],
    interests: ["Generative AI", "Reasoning Models", "Autonomous Agents", "Robotics"],
    created_at: "2025-02-01T11:20:00Z",
    updated_at: "2026-03-03T10:00:00Z",
    connection_status: "none",
    mutual_connections_count: 14,
  },
  {
    id: "usr_5",
    username: "david_okoye",
    full_name: "David Okoye",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    headline: "Founder @ Synapse Bio | Computational Biology & HealthTech",
    bio: "Applying deep neural networks to protein folding simulations and drug discovery workflows. Looking for co-founders and engineers.",
    location: "Boston, MA",
    website: "https://davidokoye.xyz",
    github_url: "https://github.com/davidokoye",
    linkedin_url: "https://linkedin.com/in/davidokoye",
    skills: ["Python", "Product Management", "AI / LLMs", "GraphQL", "Docker"],
    interests: ["Biotechnology", "HealthTech", "Scientific Computing", "Startups"],
    created_at: "2025-03-01T08:00:00Z",
    updated_at: "2026-03-04T11:30:00Z",
    connection_status: "pending_sent",
    mutual_connections_count: 3,
  },
  {
    id: "usr_6",
    username: "priya_sharma",
    full_name: "Priya Sharma",
    avatar_url: "https://images.unsplash.com/photo-1534751516642-a1714f5a5b9b?w=200&auto=format&fit=crop&q=80",
    headline: "ClimateTech Innovator & Geospatial Engineer",
    bio: "Building satellite telemetry pipelines to quantify real-time reforestation and carbon sequestering impact across continents.",
    location: "Austin, TX",
    website: "https://priyasharma.eco",
    github_url: "https://github.com/priyasharma",
    linkedin_url: "https://linkedin.com/in/priyasharma",
    skills: ["Python", "TypeScript", "PostgreSQL", "Next.js", "Docker", "Data Engineering"],
    interests: ["ClimateTech", "Satellite Imagery", "Sustainability", "Open Hardware"],
    created_at: "2025-03-10T09:00:00Z",
    updated_at: "2026-03-05T14:10:00Z",
    connection_status: "none",
    mutual_connections_count: 7,
  },
];

export const MOCK_IDEAS: Idea[] = [
  {
    id: "idea_1",
    author_id: "usr_4",
    author: MOCK_PEOPLE[3],
    title: "SynapseMesh: Decentralized Collaborative Agent Swarms for Code Review",
    description:
      "A peer-to-peer network of specialized AI micro-agents that continuously analyze pull requests, verify architectural invariant tests, detect security zero-days, and suggest micro-optimizations before merge.",
    category: "AI & Machine Learning",
    tags: ["Autonomous Agents", "Code Review", "LLMs", "Developer Tools", "Open Source"],
    status: "open",
    likes_count: 142,
    comments_count: 28,
    created_at: "2026-03-01T14:20:00Z",
    updated_at: "2026-03-04T18:00:00Z",
    is_liked: true,
  },
  {
    id: "idea_2",
    author_id: "usr_6",
    author: MOCK_PEOPLE[5],
    title: "FloraTrace: Open High-Resolution Satellite Carbon Verification Ledger",
    description:
      "Using Sentinel-2 satellite hyperspectral imagery and localized ground IoT sensors to automatically verify carbon offset reforestation projects, producing cryptographic audit trails without middlemen.",
    category: "Climate & Sustainability",
    tags: ["ClimateTech", "Geospatial", "IoT", "Verification", "Satellites"],
    status: "in_progress",
    likes_count: 98,
    comments_count: 19,
    created_at: "2026-02-27T08:15:00Z",
    updated_at: "2026-03-03T11:00:00Z",
    is_liked: false,
  },
  {
    id: "idea_3",
    author_id: "usr_2",
    author: MOCK_PEOPLE[1],
    title: "CanvasFlow: Spatial Infinity Board for Collaborative Software Architecture",
    description:
      "A real-time infinite collaborative canvas designed specifically for software engineers and systems architects. Turn natural language diagrams into verified OpenAPI schemas and infrastructure-as-code manifests with live latency simulation.",
    category: "Developer Tools",
    tags: ["Design Systems", "Spatial UI", "Architecture", "Real-Time", "Canvas"],
    status: "open",
    likes_count: 215,
    comments_count: 42,
    created_at: "2026-02-25T19:00:00Z",
    updated_at: "2026-03-05T09:30:00Z",
    is_liked: true,
  },
  {
    id: "idea_4",
    author_id: "usr_5",
    author: MOCK_PEOPLE[4],
    title: "BioFold Studio: Interactive WebGL Protein Simulation for Student Researchers",
    description:
      " Democratizing structural biology research by bringing GPU-accelerated molecular dynamics simulations into the browser via WebGPU and WebAssembly, enabling high-school and university researchers to experiment with novel therapeutics.",
    category: "Health & Biotech",
    tags: ["Biotech", "WebGPU", "Education", "Simulation", "Open Science"],
    status: "open",
    likes_count: 76,
    comments_count: 12,
    created_at: "2026-03-02T16:00:00Z",
    updated_at: "2026-03-04T13:20:00Z",
    is_liked: false,
  },
  {
    id: "idea_5",
    author_id: "usr_3",
    author: MOCK_PEOPLE[2],
    title: "ZeroLog: Cryptographically Verifiable Zero-Knowledge Audit Trails for Cloud Clusters",
    description:
      "A lightweight eBPF kernel telemetry agent that produces succinct non-interactive zero-knowledge proofs (SNARKs) of operational integrity without leaking private application data or secrets.",
    category: "Security & Cloud",
    tags: ["Rust", "eBPF", "Zero Knowledge", "Security", "Cloud Infrastructure"],
    status: "implemented",
    likes_count: 164,
    comments_count: 31,
    created_at: "2026-02-20T10:45:00Z",
    updated_at: "2026-03-01T15:00:00Z",
    is_liked: false,
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj_1",
    owner_id: "usr_curr_1",
    owner: MOCK_CURRENT_USER,
    name: "IdeaEra",
    slug: "ideaera",
    description:
      "The next-generation social innovation ecosystem uniting creators, developers, founders, and innovators to turn breakthrough concepts into reality through transparent collaboration.",
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80",
    repository_url: "https://github.com/ideaera/platform",
    website_url: "https://ideaera.dev",
    status: "launched",
    technologies: ["Next.js 16", "React 19", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL"],
    members: [
      { project_id: "proj_1", user_id: "usr_curr_1", role: "Lead Architect", joined_at: "2025-01-15T10:00:00Z", user: MOCK_CURRENT_USER },
      { project_id: "proj_1", user_id: "usr_2", role: "Design Lead", joined_at: "2025-02-10T14:30:00Z", user: MOCK_PEOPLE[1] },
      { project_id: "proj_1", user_id: "usr_3", role: "Systems Engineer", joined_at: "2025-02-15T18:00:00Z", user: MOCK_PEOPLE[2] },
    ],
    created_at: "2025-01-15T10:00:00Z",
    updated_at: "2026-03-05T12:00:00Z",
  },
  {
    id: "proj_2",
    owner_id: "usr_2",
    owner: MOCK_PEOPLE[1],
    name: "Lumina Design Token Engine",
    slug: "lumina-design-engine",
    description:
      "Automated cross-platform design token sync compiler bridging Figma Variables, CSS custom properties, Tailwind presets, and React Native style constants with zero drift.",
    image_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
    repository_url: "https://github.com/sarahkim/lumina-tokens",
    website_url: "https://lumina-design.dev",
    status: "beta",
    technologies: ["TypeScript", "Rust", "Figma REST API", "Node.js", "AST Parser"],
    members: [
      { project_id: "proj_2", user_id: "usr_2", role: "Creator & Maintainer", joined_at: "2025-05-10T14:30:00Z", user: MOCK_PEOPLE[1] },
      { project_id: "proj_2", user_id: "usr_curr_1", role: "Contributor", joined_at: "2025-06-01T10:00:00Z", user: MOCK_CURRENT_USER },
    ],
    created_at: "2025-05-10T14:30:00Z",
    updated_at: "2026-03-01T17:20:00Z",
  },
  {
    id: "proj_3",
    owner_id: "usr_4",
    owner: MOCK_PEOPLE[3],
    name: "Aura Agent Runtime",
    slug: "aura-agent-runtime",
    description:
      "Ultra-fast asynchronous runtime for multi-agent reasoning and deterministic memory replay, engineered with structured schema generation and semantic caching.",
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    repository_url: "https://github.com/elenarostova/aura-runtime",
    website_url: "https://aura-agents.org",
    status: "in_development",
    technologies: ["Python", "Rust", "PyTorch", "gRPC", "Docker"],
    members: [
      { project_id: "proj_3", user_id: "usr_4", role: "Principal Researcher", joined_at: "2025-07-20T11:00:00Z", user: MOCK_PEOPLE[3] },
      { project_id: "proj_3", user_id: "usr_3", role: "Infrastructure", joined_at: "2025-08-01T16:00:00Z", user: MOCK_PEOPLE[2] },
    ],
    created_at: "2025-07-20T11:00:00Z",
    updated_at: "2026-03-03T18:40:00Z",
  },
  {
    id: "proj_4",
    owner_id: "usr_6",
    owner: MOCK_PEOPLE[5],
    name: "SatCanopy Analytics",
    slug: "satcanopy-analytics",
    description:
      "Real-time canopy density tracking using European Space Agency Copernicus imagery, serving open telemetry APIs for conservation groups.",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    repository_url: "https://github.com/priyasharma/satcanopy",
    website_url: "https://satcanopy.org",
    status: "in_development",
    technologies: ["Python", "PostgreSQL", "Next.js", "GDAL", "FastAPI"],
    members: [
      { project_id: "proj_4", user_id: "usr_6", role: "Lead Scientist", joined_at: "2025-09-12T09:00:00Z", user: MOCK_PEOPLE[5] },
    ],
    created_at: "2025-09-12T09:00:00Z",
    updated_at: "2026-03-04T14:15:00Z",
  },
];

export const MOCK_HACKATHONS: Hackathon[] = [
  {
    id: "hack_1",
    title: "Global AI Innovators Hackathon 2026",
    description:
      "Build autonomous agents, multimodal generative tools, and breakthrough intelligence apps in 48 hours. Connect with world-class mentors, angel syndicates, and fellow founders.",
    organizer: "Anthropic & Supabase",
    location: "San Francisco & Online",
    mode: "Hybrid",
    start_date: "2026-03-20T09:00:00Z",
    end_date: "2026-03-23T18:00:00Z",
    registration_url: "https://ideaera.dev/hackathons/global-ai-2026",
    image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80",
    created_at: "2026-02-15T10:00:00Z",
    tags: ["Generative AI", "Agents", "Supabase", "LLMs"],
    prizes: "$75,000 in Prizes + Seed Incubator Track",
  },
  {
    id: "hack_2",
    title: "Open Collab Hack 2026",
    description:
      "A worldwide virtual hackathon dedicated to open-source developer tooling, accessible software, and community digital infrastructure.",
    organizer: "GitHub & IdeaEra",
    location: "Global",
    mode: "Online",
    start_date: "2026-04-05T00:00:00Z",
    end_date: "2026-04-08T23:59:00Z",
    registration_url: "https://ideaera.dev/hackathons/open-collab",
    image_url: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80",
    created_at: "2026-02-20T12:00:00Z",
    tags: ["Open Source", "Developer Tools", "Web", "Rust"],
    prizes: "$50,000 in Grants & Cloud Credits",
  },
  {
    id: "hack_3",
    title: "ClimateTech Nexus Challenge",
    description:
      "Architect digital solutions, satellite data pipelines, and clean energy optimizations for planetary sustainability. Work alongside climate scientists.",
    organizer: "Earthshot Collective & MIT",
    location: "Seattle, WA",
    mode: "In-Person",
    start_date: "2026-04-18T08:00:00Z",
    end_date: "2026-04-20T20:00:00Z",
    registration_url: "https://ideaera.dev/hackathons/climate-nexus",
    image_url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    created_at: "2026-02-22T14:00:00Z",
    tags: ["ClimateTech", "CleanEnergy", "Geospatial", "IoT"],
    prizes: "$100,000 Deployment Grant Pool",
  },
  {
    id: "hack_4",
    title: "BioCompute Sprint 2026",
    description:
      "Accelerate breakthrough health discoveries and computational biology simulations. Open to bioinformaticians, engineers, and machine learning researchers.",
    organizer: "Synapse Bio & Harvard Innovation Lab",
    location: "Boston, MA & Virtual",
    mode: "Hybrid",
    start_date: "2026-05-02T10:00:00Z",
    end_date: "2026-05-04T18:00:00Z",
    registration_url: "https://ideaera.dev/hackathons/biocompute",
    image_url: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80",
    created_at: "2026-02-25T16:00:00Z",
    tags: ["Bioinformatics", "HealthTech", "WebGPU", "ML"],
    prizes: "$60,000 Research Fellowship",
  },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: "comp_1",
    name: "VoxelForge AI",
    slug: "voxelforge-ai",
    logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=200&auto=format&fit=crop&q=80",
    description:
      "Building next-generation generative spatial compute and 3D simulation tools for developers and robotics systems worldwide.",
    website: "https://voxelforge.ai",
    industry: "Artificial Intelligence",
    location: "San Francisco, CA",
    size: "45-100 People",
    tech_stack: ["PyTorch", "CUDA", "TypeScript", "React", "Rust"],
    created_at: "2024-03-10T10:00:00Z",
  },
  {
    id: "comp_2",
    name: "Synapse Bio",
    slug: "synapse-bio",
    logo_url: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=200&auto=format&fit=crop&q=80",
    description:
      "Developing computational biology pipelines and open neural interface diagnostics to pioneer generative therapeutics.",
    website: "https://synapsebio.org",
    industry: "Biotechnology",
    location: "Boston, MA",
    size: "20-50 People",
    tech_stack: ["Python", "Next.js", "PostgreSQL", "Docker", "AWS"],
    created_at: "2024-06-15T11:00:00Z",
  },
  {
    id: "comp_3",
    name: "Aether Labs",
    slug: "aether-labs",
    logo_url: "https://images.unsplash.com/photo-1534972195531-a756b1126f24?w=200&auto=format&fit=crop&q=80",
    description:
      "Decentralized verifiable computing infrastructure for privacy-first collaborative applications and zero-knowledge primitives.",
    website: "https://aetherlabs.tech",
    industry: "Web3 & Cloud",
    location: "Zurich, Switzerland",
    size: "30-75 People",
    tech_stack: ["Rust", "Solidity", "Go", "Kubernetes", "GraphQL"],
    created_at: "2023-11-20T12:00:00Z",
  },
  {
    id: "comp_4",
    name: "Hyperion Robotics",
    slug: "hyperion-robotics",
    logo_url: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=200&auto=format&fit=crop&q=80",
    description:
      "Autonomous robotics and perception systems for automated agroforestry, precision soil analysis, and regenerative farming.",
    website: "https://hyperionrobotics.io",
    industry: "Robotics & Hardware",
    location: "Austin, TX",
    size: "50-120 People",
    tech_stack: ["C++", "ROS 2", "Python", "Computer Vision", "Embedded Linux"],
    created_at: "2024-01-05T09:00:00Z",
  },
  {
    id: "comp_5",
    name: "Kite Flow",
    slug: "kite-flow",
    logo_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&auto=format&fit=crop&q=80",
    description:
      "Next-generation collaborative canvas and telemetry architecture for modern engineering, product, and distributed research squads.",
    website: "https://kiteflow.app",
    industry: "Developer Tools",
    location: "Remote / Global",
    size: "15-30 People",
    tech_stack: ["TypeScript", "WebSockets", "Canvas API", "PostgreSQL", "Next.js"],
    created_at: "2024-08-18T14:30:00Z",
  },
];

export const MOCK_CONNECTIONS: Connection[] = [
  {
    id: "conn_1",
    requester_id: "usr_curr_1",
    receiver_id: "usr_2",
    requester: MOCK_CURRENT_USER,
    receiver: MOCK_PEOPLE[1],
    status: "accepted",
    created_at: "2025-02-15T12:00:00Z",
    updated_at: "2025-02-15T14:00:00Z",
  },
  {
    id: "conn_2",
    requester_id: "usr_3",
    receiver_id: "usr_curr_1",
    requester: MOCK_PEOPLE[2],
    receiver: MOCK_CURRENT_USER,
    status: "pending",
    created_at: "2026-03-04T18:00:00Z",
    updated_at: "2026-03-04T18:00:00Z",
  },
  {
    id: "conn_3",
    requester_id: "usr_curr_1",
    receiver_id: "usr_5",
    requester: MOCK_CURRENT_USER,
    receiver: MOCK_PEOPLE[4],
    status: "pending",
    created_at: "2026-03-03T11:00:00Z",
    updated_at: "2026-03-03T11:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_1",
    user_id: "usr_curr_1",
    type: "connection_request",
    title: "New Connection Request",
    message: "Marcus Vance sent you an invitation to connect.",
    related_id: "usr_3",
    read: false,
    created_at: "2026-03-04T18:00:00Z",
  },
  {
    id: "notif_2",
    user_id: "usr_curr_1",
    type: "idea_like",
    title: "Idea Liked",
    message: "Sarah Kim liked your concept for SynapseMesh.",
    related_id: "idea_1",
    read: false,
    created_at: "2026-03-04T15:20:00Z",
  },
  {
    id: "notif_3",
    user_id: "usr_curr_1",
    type: "idea_comment",
    title: "New Comment on Idea",
    message: "Elena Rostova commented: 'The invariant test agent approach is brilliant!'",
    related_id: "idea_1",
    read: true,
    created_at: "2026-03-03T20:10:00Z",
  },
  {
    id: "notif_4",
    user_id: "usr_curr_1",
    type: "project_invite",
    title: "Project Collaboration",
    message: "You were added as a contributor to Lumina Design Token Engine.",
    related_id: "proj_2",
    read: true,
    created_at: "2026-03-01T10:00:00Z",
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: "msg_1",
    sender_id: "usr_2",
    receiver_id: "usr_curr_1",
    sender: MOCK_PEOPLE[1],
    receiver: MOCK_CURRENT_USER,
    content: "Hey Alex! I just looked through the latest IdeaEra design tokens and the dark mode contrast feels fantastic.",
    created_at: "2026-03-05T14:10:00Z",
    read_at: "2026-03-05T14:12:00Z",
  },
  {
    id: "msg_2",
    sender_id: "usr_curr_1",
    receiver_id: "usr_2",
    sender: MOCK_CURRENT_USER,
    receiver: MOCK_PEOPLE[1],
    content: "Thanks Sarah! The spatial navigation transitions in CanvasFlow look incredible as well. Are you planning to present it at the Global AI hackathon?",
    created_at: "2026-03-05T14:15:00Z",
    read_at: "2026-03-05T14:16:00Z",
  },
  {
    id: "msg_3",
    sender_id: "usr_2",
    receiver_id: "usr_curr_1",
    sender: MOCK_PEOPLE[1],
    receiver: MOCK_CURRENT_USER,
    content: "Yes, definitely! We should team up and connect our agent runtime with the infinite canvas interface.",
    created_at: "2026-03-05T14:18:00Z",
    read_at: null,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    other_user: MOCK_PEOPLE[1],
    last_message: MOCK_MESSAGES[2],
    unread_count: 1,
  },
  {
    other_user: MOCK_PEOPLE[3],
    last_message: {
      id: "msg_elena_1",
      sender_id: "usr_4",
      receiver_id: "usr_curr_1",
      sender: MOCK_PEOPLE[3],
      receiver: MOCK_CURRENT_USER,
      content: "Would love to discuss test-time compute benchmarks when you have a moment.",
      created_at: "2026-03-04T17:40:00Z",
      read_at: "2026-03-04T18:00:00Z",
    },
    unread_count: 0,
  },
];
